"""Create sessions and session_stocks

Revision ID: ee5d5ad537a1
Revises: 
Create Date: 2023-06-28 18:10:57.317298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee5d5ad537a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_stock',
    sa.Column('session_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ticker', sa.String(length=5), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'ticker'),
    sa.UniqueConstraint('session_id', 'ticker', name='unique_config')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_stock')
    op.drop_table('sessions')
    # ### end Alembic commands ###
